services:
  - type: web
    name: faff-backend
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd basiclogin && gunicorn basiclogin.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: TIME_ZONE
        value: "Asia/Kolkata"
      - key: API_BASE_URL
        fromService:
          name: faff-backend
          type: web
          property: host
      - key: WEBHOOK_URL
        fromService:
          name: faff-backend
          type: web
          property: host
        value: "${API_BASE_URL}/webhooks/messages"
      - key: DATABASE_URL
        fromDatabase:
          name: faff-db
          property: connectionString

databases:
  - name: faff-db
    databaseName: faff
    user: faff_user
